{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "trek.fullname" . }}-data
  labels:
    app: {{ include "trek.name" . }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.persistence.data.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "trek.fullname" . }}-uploads
  labels:
    app: {{ include "trek.name" . }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.persistence.uploads.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.uploads.size }}
{{- end }}
